#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [2]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [3]:
def symmetric(A):
    row=0
    col=0
    result=0
    while row<np.shape(A)[0]:
        col=0
        while col<np.shape(A)[1]:
            if A[row,col]==A[col,row]:
                #defining 0 here as True
                result+=0
            else:
                #defining 1 here as false
                result+=1
            col=col+1
        row=row+1
    
    if result==0:
        print( 'Matrix is symmetric')
    else:
        print('Matrix is not symmetric')

Test your function on the two matrices below

In [4]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [5]:
symmetric(SymMatrix)

Matrix is symmetric


In [6]:
symmetric(A)

Matrix is not symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [7]:
def trans(A):
    sym=np.zeros(np.shape(A))
    r1=np.shape(A)[0]
    c1= np.shape(A)[1]
    for r in range(r1):
        for c in range(c1):
            sym[c][r]=A[r][c] 
    return sym

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [10]:
A = np.random.rand(6,6);
at=trans(A)

result=0
for r2 in range(np.shape(A)[0]):
    for c2 in range(np.shape(A)[1]):
        if at[r2,c2]==A[r2,c2]:
            result+=0
        else:
            result+=1
            
print(result,'is the result and since this is not 0 this means they are not equal as their elements are not equal')

30 is the result and since this is not 0 this means they are not equal as their elements are not equal


In [10]:
print(trans(at)-A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
#this returns a zero matrix so the statement above is true

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [12]:
def maxentry(A):
    #defining row and column and max =0
    ro=0
    co=0
    maxi=0
    while ro<np.shape(A)[0]:
        co=0
        while co<np.shape(A)[1]:
            if A[ro,co]>maxi:
                #comparing each value
                maxi=A[ro,co]
            else:
                maxi=maxi
            co+=1
        ro+=1
    return maxi
                

Check your result by comparing to `np.max(A)` for the below random matrix

In [13]:
A = np.random.rand(4,5)

print(A)

[[0.76484981 0.63713646 0.9723118  0.84342274 0.52544308]
 [0.44775053 0.3563131  0.83162488 0.65437322 0.28403704]
 [0.89907523 0.09806489 0.05818207 0.49782331 0.69385466]
 [0.499123   0.03351181 0.75948387 0.35742419 0.94278097]]


In [14]:
maxentry(A)

0.9723117993318755

In [15]:
# we can see here this lines up as our maximum value of A

Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [16]:
def L1norm(A):
    it=0
    comp=0
    sume=0
    while it<np.shape(A)[1]:
        for ii in np.abs(A[:,it]):
            sume=sume+ii
            if comp<sume:
                comp=sume
            else:
                comp=comp
        it=it+1
        sume=0
    return comp

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [17]:
A = np.random.rand(3,4)
print(A)

[[0.81031174 0.356192   0.51247032 0.06578638]
 [0.07643646 0.37595683 0.95625465 0.87604207]
 [0.3685349  0.94096671 0.28231156 0.34291033]]


In [18]:
print(A[0,:])

[0.81031174 0.356192   0.51247032 0.06578638]


In [19]:
print(L1norm(A))

1.7510365213288923


In [20]:
la.norm(A,1)

1.7510365213288923

## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [21]:
def Linfnorm(A):
    jt=0
    comp1=0
    sume1=0
    while jt<np.shape(A)[0]:
        for ii1 in np.abs(A[jt,:]):
            sume1=sume1+ii1
            if comp1<sume1:
                comp1=sume1
            else:
                comp1=comp1
        jt=jt+1
        sume1=0
    return comp1

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [22]:
A = np.random.rand(3,4)

print(A)

[[0.50145777 0.10897705 0.17191384 0.17261011]
 [0.50650028 0.8216647  0.324274   0.19156752]
 [0.40434155 0.63456816 0.63436554 0.07838856]]


In [23]:
print(Linfnorm(A))

1.8440064932617626


In [24]:
print(la.norm(A,np.inf))

1.8440064932617626


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [25]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [26]:
la.cond(A1)

13334936994.070848

In [27]:
#We can see here that A1 is ill conditioned since its conditional number is huge comapred to A2 and A3.
#This means that the matrix is almost singular and that any calculation of its inverse or any other calculation, will
# be prone to large errors.

In [28]:
la.cond(A2)

21.552466488381846

In [29]:
la.cond(A3)

15.12244969941062

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [51]:
def L2Norm(v):
    return la.norm(v,2)

In [52]:
b=np.array([1,2,3,4])
db=np.array([.1,0,0,0])

In [53]:
x1=la.inv(A1)@b
dx1=la.inv(A1)@db

In [54]:
x2=la.inv(A2)@b
dx2=la.inv(A2)@db

In [55]:
print('Change in b = ',(100*L2Norm(db)/L2Norm(b)),'%')

Change in b =  1.8257418583505538 %


In [56]:
print('Change in x = ',(100*L2Norm(dx1)/L2Norm(x1)),'% for A1')
print('Change in x = ',((100*L2Norm(dx2)/L2Norm(x2))),'% for A2')

Change in x =  512.6206098890642 % for A1
Change in x =  10.483582220339125 % for A2


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [35]:
# Answer here

# The system A1 is more sensitive to small changes in b as from above we can see that the conditional number is 
# extremely large which means that small perturbations and calculations will result in large errors.

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [36]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [37]:
evals=la.eig(A)[0]
evect=la.eig(A)[1]

In [38]:
#print in decseding order
print(np.sort(evals)[::-1])

[15.78569318  1.26595327 -2.05164645]


In [39]:
print(np.sum(abs(np.dot(A,evect[:,0]))),'=',np.sum(abs(evect[:,0]*evals[0])),'for the first pair of eigenvalues and eigenvectors')



25.92176036654898 = 25.921760366548977 for the first pair of eigenvalues and eigenvectors


In [40]:
print(np.sum(abs(np.dot(A,evect[:,1]))),'=',np.sum(abs(evect[:,1]*evals[1])),'for the second pair of eigenvalues and eigenvectors')


3.1086597329246555 = 3.108659732924656 for the second pair of eigenvalues and eigenvectors


In [41]:
print(np.sum(abs(np.dot(A,evect[:,2]))),'=',np.sum(abs(evect[:,2]*evals[2])),'for the third pair of eigenvalues and eigenvectors')


1.8958724833496188 = 1.8958724833496179 for the third pair of eigenvalues and eigenvectors


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [42]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [43]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)

In [44]:
maxe=MaxEigenvalue(A, 1e-14)
Lam1 = maxe[0]
e1 = maxe[1]
print(Lam1,'is the first eigenvalue')
print(e1,'is the first eigenvector')

5.172971199844755 is the first eigenvalue
[0.71538265 0.43087578 0.40381884 0.37350243] is the first eigenvector


In [45]:
B = A - Lam1*np.outer(e1, e1)

In [46]:
maxe2=MaxEigenvalue(B, 1e-14)
Lam2 = maxe2[0]
e2 = maxe2[1]
print(Lam2,'is the second eigenvalue')
print(e2,'is the second eigenvector')

0.48166927031065454 is the second eigenvalue
[-0.04054566 -0.52331841  0.8247703  -0.21035172] is the second eigenvector


In [47]:
C = B - Lam2*np.outer(e2, e2)

In [48]:
maxe3=MaxEigenvalue(C, 1e-14)
Lam3 = maxe3[0]
e3 = maxe3[1]
print(Lam3,'is the third eigenvalue')
print(e3,'is the third eigenvector')

0.19862278268099293 is the third eigenvalue
[-0.14168212  0.64758013  0.22152221 -0.71518813] is the third eigenvector


In [49]:
D = C - Lam3*np.outer(e3, e3)

In [50]:
maxe4=MaxEigenvalue(D, 1e-14)
Lam4 = maxe4[0]
e4 = maxe4[1]
print(Lam4,'is the fourth eigenvalue')
print(e4,'is the fourth eigenvector')

0.0015297971635957561 is the fourth eigenvalue
[-0.68301529  0.34802856  0.328043    0.55204531] is the fourth eigenvector


Check your answers against Numpy's results from `la.eig(A)`

In [51]:
la.eig(A)

(array([5.17297120e+00, 1.52979716e-03, 1.98622783e-01, 4.81669270e-01]),
 array([[ 0.71538265,  0.68301529,  0.14168212, -0.04054567],
        [ 0.43087578, -0.34802856, -0.64758011, -0.52331842],
        [ 0.40381884, -0.328043  , -0.22152224,  0.82477029],
        [ 0.37350243, -0.55204531,  0.71518814, -0.21035171]]))

In [52]:
#As we can see our answers are approximately the same 

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.